#!/bin/bash
#SBATCH --job-name=adcprep              # Job Name
#SBATCH --output=adcprep.%j.out         # Standard output log
#SBATCH --error=adcprep.%j.err          # Standard error log
#SBATCH --partition=batch               # Partition (queue) name
#SBATCH --nodes=1                       # Number of nodes
#SBATCH --ntasks=1                      # Number of MPI tasks
#SBATCH --ntasks-per-node=1             # How many tasks on each node
#SBATCH --cpus-per-task=1               # Number of cores per MPI rank
#SBATCH --mem-per-cpu=16000mb           # Memory limit per processor
#SBATCH --time=01:00:00                 # Time limit hh:mm:ss

ADCHOME=/work/engr8990/instructor_data/adcirc/adcirc-noaa.stofs.2d.glo.v1.1.0r2-install/bin

ml netCDF-Fortran

cd $SLURM_SUBMIT_DIR

date > prep.begin
$ADCHOME/adcprep --np 12 --partmesh >& $SLURM_JOB_NAME.out
$ADCHOME/adcprep --np 12 --prepall >> $SLURM_JOB_NAME.out
date > prep.end

exit 0
